### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by Destaq** [Mothrakk/cross-pollinate#1]
I followed the steps in the README. I've tried inserting my token both with and without quotes. However, I always get the following output:
```bash
Traceback (most recent call last):
  File "main.py", line 62, in <module>
    client.run(token, bot=False)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/discord/client.py", line 640, in run
    return future.result()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/discord/client.py", line 621, in runner
    await self.start(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/discord/client.py", line 585, in start
    await self.connect(reconnect=reconnect)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/discord/client.py", line 499, in connect
    await self._connect()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/discord/client.py", line 463, in _connect
    await self.ws.poll_event()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/discord/gateway.py", line 471, in poll_event
    await self.received_message(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/discord/gateway.py", line 425, in received_message
    func(data)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/discord/state.py", line 394, in parse_ready
    guild = self._add_guild_from_data(guild_data)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/discord/state.py", line 274, in _add_guild_from_data
    guild = Guild(data=guild, state=self)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/discord/guild.py", line 177, in __init__
    self._from_data(data)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/discord/guild.py", line 297, in _from_data
    self._sync(guild)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/discord/guild.py", line 324, in _sync
    self._add_channel(TextChannel(guild=self, data=c, state=self._state))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/discord/channel.py", line 107, in __init__
    self._update(guild, data)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/discord/channel.py", line 131, in _update
    self._fill_overwrites(data)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/discord/abc.py", line 294, in _fill_overwrites
    self._overwrites.append(_Overwrites(id=overridden_id, **overridden))
TypeError: __new__() got an unexpected keyword argument 'deny_new'
```

**Comment by loigom** [comment]
That error derives from you having an outdated version of discord.py. But the script won't work anyways as it's 10 months old and Discord has gotten more restrictive with user scraping.
